SHOW databases;
use atishay;
show tables;
select * from 118bh2;
desc 118bh2

-- TIME AND DATE FUNCTIONS CAN BE USED IN MYSQL
-- THE DATE FORMAT IS "YYYY-MM-DD"
-- THE TIME FORMAT IS "HH:MM:SS"

-- ENTERING OF A VLUE IN THE TABLE
-- INSERT INTO 118BH2 VALUES("ATISHAY JAIN", "2003-04-07", "14:30:00");
